# Generated by Django 3.0.5 on 2020-04-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickbait', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clickbait',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='clickbait',
            field=models.FloatField(default=0.0),
        ),
    ]
