# Generated by Django 3.0.5 on 2020-04-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickbait', '0002_auto_20200414_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='link',
            new_name='handle',
        ),
    ]
